### ISSUE TITLE
auto-complete shows names "names" and "NameError", Py is case sensitive

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_python_intel#7]
![Screenshot from 2020-05-14 18-00-42](https://user-images.githubusercontent.com/4154978/81950687-f0af0f80-960c-11ea-97d1-8f233b9000ef.png)

**Comment by Alexey-T** [comment]
![Screenshot from 2020-05-14 18-06-25](https://user-images.githubusercontent.com/4154978/81951304-ae3a0280-960d-11ea-89ad-9dc83d6c803c.png)

**Comment by OlehL** [comment]
Это удобно.
